package net.minecraft.theTitans;

import net.minecraft.item.Food;
import net.minecraft.potion.EffectInstance;
import net.minecraft.potion.Effects;

public class TitanFoods {
    public static final Food golden_potatoe = new Food.Builder()
            .effect(new EffectInstance(Effects.REGENERATION, 5, 1), 1.0f)
            .effect(new EffectInstance(Effects.ABSORPTION, 2400, 0), 1.0F)
            .nutrition(6)
            .saturationMod(1.2f)
            .alwaysEat()
            .build();
    public static final Food golden_bread = new Food.Builder()
            .effect(new EffectInstance(Effects.REGENERATION, 5, 1), 1.0f)
            .effect(new EffectInstance(Effects.ABSORPTION, 2400, 0), 1.0F)
            .nutrition(5)
            .saturationMod(1.2f)
            .alwaysEat()
            .build();
    public static final Food golden_cookie = new Food.Builder()
            .effect(new EffectInstance(Effects.REGENERATION, 5, 1), 1.0f)
            .effect(new EffectInstance(Effects.ABSORPTION, 2400, 0), 1.0F)
            .nutrition(2)
            .saturationMod(1.2f)
            .alwaysEat()
            .build();
    public static final Food golden_melon = new Food.Builder()
            .effect(new EffectInstance(Effects.REGENERATION, 5, 1), 1.0f)
            .effect(new EffectInstance(Effects.ABSORPTION, 2400, 0), 1.0F)
            .nutrition(2)
            .saturationMod(1.2f)
            .alwaysEat()
            .build();
    public static final Food golden_pumpkin_pie = new Food.Builder()
            .effect(new EffectInstance(Effects.REGENERATION, 5, 1), 1.0f)
            .effect(new EffectInstance(Effects.ABSORPTION, 2400, 0), 1.0F)
            .nutrition(8)
            .saturationMod(1.2f)
            .alwaysEat()
            .build();
    public static final Food apple_diamond = new Food.Builder()
            .effect(new EffectInstance(Effects.ABSORPTION, 6000, 9), 1.0F)
            .effect(new EffectInstance(Effects.REGENERATION, 100, 2), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.MOVEMENT_SPEED, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.DIG_SPEED, 2000, 0), 1.0f)
            .nutrition(4)
            .saturationMod(2.4f)
            .alwaysEat()
            .build();
    public static final Food diamond_potatoe = new Food.Builder()
            .effect(new EffectInstance(Effects.ABSORPTION, 6000, 9), 1.0F)
            .effect(new EffectInstance(Effects.REGENERATION, 100, 2), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.MOVEMENT_SPEED, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.DIG_SPEED, 2000, 0), 1.0f)
            .nutrition(6)
            .saturationMod(2.4f)
            .alwaysEat()
            .build();
    public static final Food diamond_bread = new Food.Builder()
            .effect(new EffectInstance(Effects.ABSORPTION, 6000, 9), 1.0F)
            .effect(new EffectInstance(Effects.REGENERATION, 100, 2), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.MOVEMENT_SPEED, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.DIG_SPEED, 2000, 0), 1.0f)
            .nutrition(5)
            .saturationMod(2.4f)
            .alwaysEat()
            .build();
    public static final Food diamond_cookie = new Food.Builder()
            .effect(new EffectInstance(Effects.ABSORPTION, 6000, 9), 1.0F)
            .effect(new EffectInstance(Effects.REGENERATION, 100, 2), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.MOVEMENT_SPEED, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.DIG_SPEED, 2000, 0), 1.0f)
            .nutrition(2)
            .saturationMod(2.4f)
            .alwaysEat()
            .build();
    public static final Food diamond_melon = new Food.Builder()
            .effect(new EffectInstance(Effects.ABSORPTION, 6000, 9), 1.0F)
            .effect(new EffectInstance(Effects.REGENERATION, 100, 2), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.MOVEMENT_SPEED, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.DIG_SPEED, 2000, 0), 1.0f)
            .nutrition(2)
            .saturationMod(2.4f)
            .alwaysEat()
            .build();
    public static final Food diamond_pumpkin_pie = new Food.Builder()
            .effect(new EffectInstance(Effects.ABSORPTION, 6000, 9), 1.0F)
            .effect(new EffectInstance(Effects.REGENERATION, 100, 2), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.MOVEMENT_SPEED, 2000, 0), 1.0f)
            .effect(new EffectInstance(Effects.DIG_SPEED, 2000, 0), 1.0f)
            .nutrition(8)
            .saturationMod(2.4f)
            .alwaysEat()
            .build();
    public static final Food enchanted_golden_potatoe = new Food.Builder()
            .effect(new EffectInstance(Effects.REGENERATION, 600, 4), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 6000, 0), 1.0F)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 0), 1.0F)
            .effect(new EffectInstance(Effects.ABSORPTION, 2400, 3), 1.0F)
            .nutrition(6)
            .saturationMod(1.2f)
            .alwaysEat()
            .build();
    public static final Food enchanted_golden_bread = new Food.Builder()
            .effect(new EffectInstance(Effects.REGENERATION, 600, 4), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 6000, 0), 1.0F)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 0), 1.0F)
            .effect(new EffectInstance(Effects.ABSORPTION, 2400, 3), 1.0F)
            .nutrition(5)
            .saturationMod(1.2f)
            .alwaysEat()
            .build();
    public static final Food enchanted_golden_cookie = new Food.Builder()
            .effect(new EffectInstance(Effects.REGENERATION, 600, 4), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 6000, 0), 1.0F)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 0), 1.0F)
            .effect(new EffectInstance(Effects.ABSORPTION, 2400, 3), 1.0F)
            .nutrition(2)
            .saturationMod(1.2f)
            .alwaysEat()
            .build();
    public static final Food enchanted_golden_melon = new Food.Builder()
            .effect(new EffectInstance(Effects.REGENERATION, 600, 4), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 6000, 0), 1.0F)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 0), 1.0F)
            .effect(new EffectInstance(Effects.ABSORPTION, 2400, 3), 1.0F)
            .nutrition(2)
            .saturationMod(1.2f)
            .alwaysEat()
            .build();
    public static final Food enchanted_golden_pumpkin_pie = new Food.Builder()
            .effect(new EffectInstance(Effects.REGENERATION, 600, 4), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 6000, 0), 1.0F)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 0), 1.0F)
            .effect(new EffectInstance(Effects.ABSORPTION, 2400, 3), 1.0F)
            .nutrition(8)
            .saturationMod(1.2f)
            .alwaysEat()
            .build();
    public static final Food enchanted_apple_diamond = new Food.Builder()
            .effect(new EffectInstance(Effects.ABSORPTION, 6000, 9), 1.0F)
            .effect(new EffectInstance(Effects.REGENERATION, 1200, 9), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_BOOST, 3000, 2), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 6000, 2), 1.0f)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 0), 1.0f)
            .effect(new EffectInstance(Effects.MOVEMENT_SPEED, 6000, 1), 1.0f)
            .effect(new EffectInstance(Effects.DIG_SPEED, 6000, 1), 1.0f)
            .nutrition(4)
            .saturationMod(2.4f)
            .alwaysEat()
            .build();
    public static final Food enchanted_diamond_potatoe = new Food.Builder()
            .effect(new EffectInstance(Effects.ABSORPTION, 6000, 9), 1.0F)
            .effect(new EffectInstance(Effects.REGENERATION, 1200, 9), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_BOOST, 3000, 2), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 6000, 2), 1.0f)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 0), 1.0f)
            .effect(new EffectInstance(Effects.MOVEMENT_SPEED, 6000, 1), 1.0f)
            .effect(new EffectInstance(Effects.DIG_SPEED, 6000, 1), 1.0f)
            .nutrition(6)
            .saturationMod(2.4f)
            .alwaysEat()
            .build();
    public static final Food enchanted_diamond_bread = new Food.Builder()
            .effect(new EffectInstance(Effects.ABSORPTION, 6000, 9), 1.0F)
            .effect(new EffectInstance(Effects.REGENERATION, 1200, 9), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_BOOST, 3000, 2), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 6000, 2), 1.0f)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 0), 1.0f)
            .effect(new EffectInstance(Effects.MOVEMENT_SPEED, 6000, 1), 1.0f)
            .effect(new EffectInstance(Effects.DIG_SPEED, 6000, 1), 1.0f)
            .nutrition(5)
            .saturationMod(2.4f)
            .alwaysEat()
            .build();
    public static final Food enchanted_diamond_cookie = new Food.Builder()
            .effect(new EffectInstance(Effects.ABSORPTION, 6000, 9), 1.0F)
            .effect(new EffectInstance(Effects.REGENERATION, 1200, 9), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_BOOST, 3000, 2), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 6000, 2), 1.0f)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 0), 1.0f)
            .effect(new EffectInstance(Effects.MOVEMENT_SPEED, 6000, 1), 1.0f)
            .effect(new EffectInstance(Effects.DIG_SPEED, 6000, 1), 1.0f)
            .nutrition(2)
            .saturationMod(2.4f)
            .alwaysEat()
            .build();
    public static final Food enchanted_diamond_melon = new Food.Builder()
            .effect(new EffectInstance(Effects.ABSORPTION, 6000, 9), 1.0F)
            .effect(new EffectInstance(Effects.REGENERATION, 1200, 9), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_BOOST, 3000, 2), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 6000, 2), 1.0f)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 0), 1.0f)
            .effect(new EffectInstance(Effects.MOVEMENT_SPEED, 6000, 1), 1.0f)
            .effect(new EffectInstance(Effects.DIG_SPEED, 6000, 1), 1.0f)
            .nutrition(2)
            .saturationMod(2.4f)
            .alwaysEat()
            .build();
    public static final Food enchanted_diamond_pumpkin_pie = new Food.Builder()
            .effect(new EffectInstance(Effects.ABSORPTION, 6000, 9), 1.0F)
            .effect(new EffectInstance(Effects.REGENERATION, 1200, 9), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_BOOST, 3000, 2), 1.0f)
            .effect(new EffectInstance(Effects.DAMAGE_RESISTANCE, 6000, 2), 1.0f)
            .effect(new EffectInstance(Effects.FIRE_RESISTANCE, 6000, 0), 1.0f)
            .effect(new EffectInstance(Effects.MOVEMENT_SPEED, 6000, 1), 1.0f)
            .effect(new EffectInstance(Effects.DIG_SPEED, 6000, 1), 1.0f)
            .nutrition(8)
            .saturationMod(2.4f)
            .alwaysEat()
            .build();
}
