package net.minecraft.theTitans.models;


import com.mojang.blaze3d.matrix.MatrixStack;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.entity.titan.EntityZombieTitan;
import net.minecraft.util.math.MathHelper;
import thehippomaster.AnimationAPI.IAnimatedEntity;
import thehippomaster.AnimationAPI.client.Animator;

public class ModelZombieTitan extends ModelTitanBase<EntityZombieTitan> {
    private final Animator animator;
    public ModelRenderer Torso;
    public ModelRenderer LeftThigh;
    public ModelRenderer RightThigh;
    public ModelRenderer MiddleBody;
    public ModelRenderer TopBody;
    public ModelRenderer Head;
    public ModelRenderer Head2;
    public ModelRenderer Head3;
    public ModelRenderer Head22;
    public ModelRenderer LeftShoulder;
    public ModelRenderer RightShoulder;
    public ModelRenderer LeftForearm;
    public ModelRenderer RightForearm;
    public ModelRenderer HeldItem;
    public ModelRenderer LeftCalf;
    public ModelRenderer RightCalf;
    public ModelRenderer Nose;
    public ModelRenderer Nose2;
    private float partialTick;

    public ModelZombieTitan() {
        this(0.0f);
    }

    public ModelZombieTitan(final float p_i1147_1_) {
        this.texWidth = 64;
        this.texHeight = 64;
        this.LeftShoulder = new ModelRenderer(this, 40, 16);
        this.LeftShoulder.mirror = true;
        this.LeftShoulder.setPos(6.0f, -2.0f, 0.0f);
        this.LeftShoulder.addBox(-2.0f, -2.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        (this.RightShoulder = new ModelRenderer(this, 40, 16)).setPos(-6.0f, -2.0f, 0.0f);
        this.RightShoulder.addBox(-2.0f, -2.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        (this.RightForearm = new ModelRenderer(this, 40, 26)).setPos(0.0f, 4.0f, 0.0f);
        this.RightForearm.addBox(-2.0f, 0.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        (this.TopBody = new ModelRenderer(this, 16, 16)).setPos(0.0f, -4.0f, 0.0f);
        this.TopBody.addBox(-4.0f, -4.0f, -2.0f, 8, 4, 4, p_i1147_1_);
        this.LeftForearm = new ModelRenderer(this, 40, 26);
        this.LeftForearm.mirror = true;
        this.LeftForearm.setPos(0.0f, 4.0f, 0.0f);
        this.LeftForearm.addBox(-2.0f, 0.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        (this.MiddleBody = new ModelRenderer(this, 16, 24)).setPos(0.0f, -4.0f, 0.0f);
        this.MiddleBody.addBox(-4.0f, -4.0f, -2.0f, 8, 4, 4, p_i1147_1_);
        (this.RightThigh = new ModelRenderer(this, 0, 16)).setPos(-2.0f, 12.0f, 0.0f);
        this.RightThigh.addBox(-2.0f, 0.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        (this.RightCalf = new ModelRenderer(this, 0, 26)).setPos(0.0f, 6.0f, 0.0f);
        this.RightCalf.addBox(-2.0f, 0.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        (this.HeldItem = new ModelRenderer(this, 32, 32)).setPos(0.0f, 4.0f, 0.0f);
        this.HeldItem.addBox(0.0f, -12.0f, -12.0f, 0, 16, 16, 0.0f);
        (this.Torso = new ModelRenderer(this, 16, 32)).setPos(0.0f, 12.0f, 0.0f);
        this.Torso.addBox(-4.0f, -4.0f, -2.0f, 8, 4, 4, p_i1147_1_);
        this.LeftThigh = new ModelRenderer(this, 0, 16);
        this.LeftThigh.mirror = true;
        this.LeftThigh.setPos(2.0f, 12.0f, 0.0f);
        this.LeftThigh.addBox(-2.0f, 0.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        this.LeftCalf = new ModelRenderer(this, 0, 26);
        this.LeftCalf.mirror = true;
        this.LeftCalf.setPos(0.0f, 6.0f, 0.0f);
        this.LeftCalf.addBox(-2.0f, 0.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        this.RightThigh.addChild(this.RightCalf);
        this.TopBody.addChild(this.LeftShoulder);
        this.TopBody.addChild(this.RightShoulder);
        this.LeftThigh.addChild(this.LeftCalf);
        this.RightShoulder.addChild(this.RightForearm);
        this.MiddleBody.addChild(this.TopBody);
        this.LeftShoulder.addChild(this.LeftForearm);
        this.Torso.addChild(this.MiddleBody);
        this.RightForearm.addChild(this.HeldItem);
        (this.Head = new ModelRenderer(this, 0, 0)).setPos(0.0f, -4.0f, 0.0f);
        this.Head.addBox(-4.0f, -8.0f, -4.0f, 8, 8, 8, p_i1147_1_);
        this.TopBody.addChild(this.Head);
        (this.Nose = new ModelRenderer(this, 24, 40)).setPos(0.0f, -2.0f, -4.0f);
        this.Nose.addBox(-1.0f, -1.0f, -2.0f, 2, 4, 2, p_i1147_1_);
        (this.Head2 = new ModelRenderer(this, 0, 40)).addBox(-4.0f, -10.0f, -4.0f, 8, 10, 8, p_i1147_1_);
        this.Head2.addChild(this.Nose);
        this.Head.addChild(this.Head2);
        (this.Head3 = new ModelRenderer(this, 0, 0)).addBox(-4.0f, -10.0f, -4.0f, 8, 8, 8, p_i1147_1_ + 2.0f);
        this.Head.addChild(this.Head3);
        (this.Nose2 = new ModelRenderer(this, 24, 40)).setPos(0.0f, -2.0f, -4.0f);
        this.Nose2.addBox(-1.0f, -2.0f, -4.0f, 2, 4, 2, p_i1147_1_);
        (this.Head22 = new ModelRenderer(this, 0, 40)).addBox(-4.0f, -12.0f, -4.0f, 8, 10, 8, p_i1147_1_ + 2.0f);
        this.Head22.addChild(this.Nose2);
        this.Head.addChild(this.Head22);
        this.animator = new Animator(this);
    }

    @Override
    public void prepareMobModel(EntityZombieTitan p_212843_1_, float p_212843_2_, float p_212843_3_, float p_212843_4_) {
        this.partialTick = p_212843_4_;
	    p_212843_1_.head.boneRegistry(this.Head, this.TopBody);
		p_212843_1_.body.boneRegistry(this.Torso);
		p_212843_1_.leftArm.boneRegistry(this.LeftShoulder);
		p_212843_1_.rightArm.boneRegistry(this.RightShoulder);
		p_212843_1_.leftLeg.boneRegistry(this.LeftThigh);
		p_212843_1_.rightLeg.boneRegistry(this.RightThigh);
        super.prepareMobModel(p_212843_1_, p_212843_2_, p_212843_3_, p_212843_4_);
    }

    public void setupAnim(final EntityZombieTitan entity, final float f, final float f1, final float f2, final float f3, final float f4) {
        this.animate(entity, f, f1, f2, f3, f4);
        this.HeldItem.visible = entity.isArmed();
        this.Head2.visible = entity.isVillager();
        if (entity.isBaby()) {
            this.Head2.visible = false;
            if (entity.isVillager()) {
                this.Head22.visible = true;
                this.Head3.visible = false;
            } else {
                this.Head22.visible = false;
                this.Head3.visible = true;
            }
        } else {
            this.Head22.visible = false;
            this.Head3.visible = false;
        }
    }

	@Override
	public ModelRenderer[] getChilds() {
		return new ModelRenderer[] {
			this.Torso, 
			this.LeftShoulder,
			this.LeftForearm,
			this.RightShoulder,
			this.RightForearm,
			this.HeldItem, 
			this.MiddleBody, 
			this.TopBody, 
			this.Head, 
			this.LeftThigh, 
			this.LeftCalf,
			this.RightThigh,
			this.RightCalf
		};
	}

    @Override
    public void renderToBuffer(MatrixStack p_225598_1_, IVertexBuilder p_225598_2_, int p_225598_3_, int p_225598_4_, float p_225598_5_, float p_225598_6_, float p_225598_7_, float p_225598_8_) {
		this.Torso.render(p_225598_1_, p_225598_2_, p_225598_3_, p_225598_4_, p_225598_5_, p_225598_6_, p_225598_7_, p_225598_8_);
        this.LeftThigh.render(p_225598_1_, p_225598_2_, p_225598_3_, p_225598_4_, p_225598_5_, p_225598_6_, p_225598_7_, p_225598_8_);
        this.RightThigh.render(p_225598_1_, p_225598_2_, p_225598_3_, p_225598_4_, p_225598_5_, p_225598_6_, p_225598_7_, p_225598_8_);
    }

    public void setAngles() {
        this.LeftShoulder.xRot = -1.5707964f;
        this.RightShoulder.xRot = -1.5707964f;
        this.HeldItem.xRot = 0.7853982f;
        this.RightThigh.z = 0.0f;
        this.LeftThigh.z = 0.0f;
        this.Torso.z = 0.0f;
        this.Torso.x = 0.0f;
        this.Torso.y = 12.0f;
        this.HeldItem.z = 0.0f;
        this.HeldItem.x = 0.0f;
        this.HeldItem.y = 4.0f;
        this.RightThigh.y = 12.0f;
        this.LeftThigh.y = 12.0f;
    }

    public void animate(final IAnimatedEntity entity, final float f, float f1, final float f2, final float f3, final float f4) {
        final EntityZombieTitan entitytitan = (EntityZombieTitan) entity;
        if (!entitytitan.isOnGround()) {
            f1 = 0.0f;
        }
        this.animator.update(entity, this.partialTick);
        this.setAngles();
        final float fo = 0.16655f;
        if (entitytitan.deathTicks <= 0) {
            final float f6 = MathHelper.cos(f2 * 0.1f);
            if (entitytitan.getAnimID() == 0) {
                this.MiddleBody.xRot = (0.001f + 0.005f * f6) * 3.1415927f;
                this.TopBody.xRot = (0.001f + 0.005f * f6) * 3.1415927f;
                this.Head.xRot = (0.001f + 0.0075f * f6) * 3.1415927f;
                this.RightShoulder.yRot = (-0.001f + 0.01f * f6) * 3.1415927f;
                this.LeftShoulder.yRot = (0.001f + -0.01f * f6) * 3.1415927f;
            }
            if (entitytitan.getVehicle() != null) {
                this.RightThigh.xRot = -1.5707964f;
                this.LeftThigh.xRot = -1.5707964f;
                this.RightThigh.yRot = 0.31415927f;
                this.LeftThigh.yRot = -0.31415927f;
                this.RightCalf.xRot = 1.0471976f;
                this.LeftCalf.xRot = 1.0471976f;
            } else if (entitytitan.getAnimID() == 0) {
                this.Nose.zRot = MathHelper.cos(f * fo - 2.0f) * 0.5f * f1;
                this.Nose2.zRot = MathHelper.cos(f * fo - 2.0f) * 0.5f * f1;
                this.Torso.zRot = MathHelper.cos(f * fo) * 0.2f * f1;
                this.MiddleBody.zRot = MathHelper.cos(f * fo - 1.0f) * 0.2f * f1;
                this.TopBody.zRot = MathHelper.cos(f * fo - 2.0f) * 0.2f * f1;
                this.RightThigh.xRot = MathHelper.cos(f * fo - 0.5f) * 0.75f * f1;
                this.LeftThigh.xRot = MathHelper.cos(f * fo + 2.6415927f) * 0.75f * f1;
                this.RightCalf.xRot = MathHelper.cos(f * fo + 3.1415927f) * 0.75f * f1;
                this.LeftCalf.xRot = MathHelper.cos(f * fo) * 0.75f * f1;
                this.Torso.y = 12.0f - MathHelper.cos(f * (fo * 2.0f) + 1.0f) * 2.0f * f1;
                this.RightThigh.y = 12.0f - MathHelper.cos(f * (fo * 2.0f) + 1.0f) * 2.0f * f1;
                this.LeftThigh.y = 12.0f - MathHelper.cos(f * (fo * 2.0f) + 1.0f) * 2.0f * f1;
                if (this.RightCalf.xRot < 0.0f) {
                    this.RightCalf.xRot = 0.0f;
                }
                if (this.LeftCalf.xRot < 0.0f) {
                    this.LeftCalf.xRot = 0.0f;
                }
            }
            final float faceYaw = f3 * 3.1415927f / 180.0f;
            final float facePitch = f4 * 3.1415927f / 180.0f;
            if (entitytitan.animID == 0) {
                final ModelRenderer head = this.Head;
                head.xRot += facePitch * 0.3f;
                final ModelRenderer head2 = this.Head;
                head2.yRot += faceYaw * 0.3f;
                final ModelRenderer topBody = this.TopBody;
                topBody.xRot += facePitch * 0.3f;
                final ModelRenderer topBody2 = this.TopBody;
                topBody2.yRot += faceYaw * 0.3f;
                final ModelRenderer middleBody = this.MiddleBody;
                middleBody.xRot += facePitch * 0.3f;
                final ModelRenderer middleBody2 = this.MiddleBody;
                middleBody2.yRot += faceYaw * 0.3f;
            } else {
                final ModelRenderer head3 = this.Head;
                head3.xRot += facePitch * 0.9f;
                final ModelRenderer head4 = this.Head;
                head4.yRot += faceYaw * 0.9f;
            }
            if (!entitytitan.isOnGround() && !entitytitan.isVehicle() && entitytitan.getY() > 1.0) {
                this.Torso.zRot = 0.0f;
                this.MiddleBody.zRot = 0.0f;
                this.TopBody.zRot = 0.0f;
                this.Head.zRot = 0.0f;
                final ModelRenderer rightShoulder = this.RightShoulder;
                rightShoulder.xRot -= entitytitan.animationSpeed;
                final ModelRenderer leftShoulder = this.LeftShoulder;
                leftShoulder.xRot -= entitytitan.animationSpeed;
                final ModelRenderer head5 = this.Head;
                head5.xRot -= entitytitan.animationSpeed;
                final ModelRenderer torso = this.Torso;
                torso.xRot += entitytitan.animationSpeed;
                this.RightThigh.zRot = 0.25f;
                this.LeftThigh.zRot = -0.25f;
                this.RightThigh.yRot = -0.25f;
                this.LeftThigh.yRot = 0.25f;
                this.RightThigh.xRot = MathHelper.cos(f2 * 0.2f) * 0.25f - (float) (entitytitan.getDeltaMovement().y / 5.0) + entitytitan.animationSpeed;
                this.LeftThigh.xRot = MathHelper.cos(f2 * 0.2f - 3.1415927f) * 0.25f - (float) (entitytitan.getDeltaMovement().y / 5.0) + entitytitan.animationSpeed;
                this.RightCalf.xRot = 0.5f - MathHelper.cos(f2 * 0.2f + 0.5f) * 0.5f;
                this.LeftCalf.xRot = 0.5f - MathHelper.cos(f2 * 0.2f - 2.6415927f) * 0.5f;
            }
            if (entitytitan.getAnimID() == 11 && entitytitan.getAnimTick() > 30 && entitytitan.getAnimTick() < 160) {
                this.Head.zRot = MathHelper.cos(f2 * 0.25f - 3.0f) * 0.5f;
                this.TopBody.zRot = MathHelper.cos(f2 * 0.25f - 2.0f) * 0.25f;
                this.MiddleBody.zRot = MathHelper.cos(f2 * 0.25f - 1.0f) * 0.25f;
                this.Torso.zRot = MathHelper.cos(f2 * 0.25f) * 0.25f;
            }
            if (entitytitan.getAnimID() == 12 && entitytitan.getAnimTick() > 30 && entitytitan.getAnimTick() < 50) {
                this.RightForearm.xRot = 0.1f * MathHelper.cos(f2 * 2.0f) * 3.1415927f;
                this.LeftForearm.xRot = -(0.1f * MathHelper.cos(f2 * 2.0f) * 3.1415927f);
            }
            if (entitytitan.getAnimID() == 1) {
                switch (entitytitan.antiTitanAttackAnimeID) {
                    case 0: {
                        this.animateAntiTitanAttack1();
                        break;
                    }
                    case 1: {
                        this.animateAntiTitanAttack2();
                        break;
                    }
                    case 2: {
                        this.animateAntiTitanAttack3();
                        break;
                    }
                    case 3: {
                        this.animateAntiTitanAttack4();
                        break;
                    }
                }
            }
            this.animateBirth();
            this.animateRoar();
            this.animateKick();
            this.animateRangedAttackThrow();
            this.animateSwordReform();
            this.animateSlam();
            this.animateLightning();
            this.animateStomp();
            this.animateDownwardSlash();
            this.animateStun();
            this.animateSidewaySlash();
        } else {
            this.animateDeath();
        }
    }

    private void animateKick() {
        this.animator.setAnim(4);
        this.animator.startPhase(30);
        this.animator.move(this.Torso, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.5f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -6.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -6.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -6.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateSwordReform() {
        this.animator.setAnim(2);
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.move(this.Torso, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, -1.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Torso, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -1.5f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.75f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.75f, -0.5f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.75f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.75f, -0.25f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.75f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.75f, -0.5f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.75f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.75f, -0.25f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.75f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.75f, -0.5f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.75f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.75f, -0.25f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -1.25f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.25f, -0.5f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.75f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.75f, -0.25f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        for (int i1 = 0; i1 < 5; ++i1) {
            this.animator.startPhase(5);
            this.animator.move(this.Torso, 0.0f, 4.0f, 0.0f);
            this.animator.move(this.RightThigh, 0.0f, 4.0f, 0.0f);
            this.animator.move(this.LeftThigh, 0.0f, 4.0f, 0.0f);
            this.animator.rotate(this.RightThigh, -1.25f, 0.5f, 0.0f);
            this.animator.rotate(this.LeftThigh, 0.25f, -0.5f, 0.0f);
            this.animator.rotate(this.RightCalf, 1.5f, 0.0f, 0.0f);
            this.animator.rotate(this.LeftCalf, 1.0f, 0.0f, 0.0f);
            this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
            this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
            this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
            this.animator.rotate(this.RightForearm, -0.1f, 0.0f, 0.0f);
            this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
            this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
            this.animator.rotate(this.MiddleBody, 0.75f, -0.25f, 0.0f);
            this.animator.rotate(this.Torso, 0.75f, -0.25f, 0.0f);
            this.animator.rotate(this.HeldItem, 1.6f, 0.0f, 0.0f);
            this.animator.endPhase();
            this.animator.startPhase(5);
            this.animator.move(this.Torso, 0.0f, 4.0f, 0.0f);
            this.animator.move(this.RightThigh, 0.0f, 4.0f, 0.0f);
            this.animator.move(this.LeftThigh, 0.0f, 4.0f, 0.0f);
            this.animator.rotate(this.RightThigh, -1.25f, 0.5f, 0.0f);
            this.animator.rotate(this.LeftThigh, 0.25f, -0.5f, 0.0f);
            this.animator.rotate(this.RightCalf, 1.5f, 0.0f, 0.0f);
            this.animator.rotate(this.LeftCalf, 1.0f, 0.0f, 0.0f);
            this.animator.rotate(this.Head, -1.75f, 0.0f, 0.0f);
            this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
            this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
            this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
            this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
            this.animator.rotate(this.TopBody, 0.4f, -0.25f, 0.0f);
            this.animator.rotate(this.MiddleBody, 0.75f, -0.25f, 0.0f);
            this.animator.rotate(this.Torso, 0.75f, -0.25f, 0.0f);
            this.animator.rotate(this.HeldItem, 1.6f, 0.0f, 0.0f);
            this.animator.endPhase();
        }
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, -0.2f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.1f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.1f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.0f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 2.0f, 0.0f, -0.75f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateSlam() {
        this.animator.setAnim(3);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 0.6f, 0.0f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.move(this.Torso, 0.0f, -1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -1.6f, 0.2f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.2f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, -0.3f, 0.0f, -0.75f);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.move(this.Torso, 0.0f, 3.0f, 1.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.5f);
        this.animator.endPhase();
        this.animator.resetPhase(30);
    }

    private void animateAntiTitanAttack1() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.5f, 0.75f, 0.75f);
        this.animator.rotate(this.RightForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, -1.5f, -0.75f, -0.75f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -8.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.0f, -1.0f);
        this.animator.rotate(this.LeftShoulder, -0.6f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 2.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack2() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 3.0f);
        this.animator.rotate(this.RightThigh, 1.0f, 0.2f, 1.6f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, -1.0f, -0.2f);
        this.animator.rotate(this.TopBody, 1.0f, 0.0f, -0.2f);
        this.animator.rotate(this.MiddleBody, 1.0f, 0.0f, -0.2f);
        this.animator.rotate(this.Torso, -2.0f, 1.0f, 0.6f);
        this.animator.rotate(this.RightShoulder, 0.8f, -0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -9.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -7.0f);
        this.animator.rotate(this.RightThigh, -3.0f, 0.2f, 1.5f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, -0.25f);
        this.animator.rotate(this.TopBody, 1.0f, 0.5f, -0.25f);
        this.animator.rotate(this.MiddleBody, 1.0f, 0.5f, -0.25f);
        this.animator.rotate(this.Torso, -2.0f, -1.0f, 0.75f);
        this.animator.rotate(this.RightShoulder, 0.8f, -0.5f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.5f, -0.75f);
        this.animator.rotate(this.RightForearm, -1.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack3() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 2.0f, -1.0f, -1.0f);
        this.animator.rotate(this.LeftForearm, -2.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -8.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.6f, 0.0f, -1.0f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, 1.0f);
        this.animator.rotate(this.RightForearm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack4() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -8.0f);
        this.animator.rotate(this.RightThigh, -3.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateLightning() {
        this.animator.setAnim(5);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 0.0f, 0.0f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.2f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, -0.2f, 0.0f);
        this.animator.rotate(this.RightCalf, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -0.4f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.2f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, -0.2f, 0.0f);
        this.animator.rotate(this.RightCalf, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -0.4f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0f, 3.0f, 1.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.9f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -0.9f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftForearm, -0.25f, 0.0f, 0.5f);
        this.animator.rotate(this.HeldItem, 2.0f, 0.0f, 2.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateStomp() {
        this.animator.setAnim(6);
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.2f, 0.75f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.2f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.5f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.5f);
        this.animator.rotate(this.TopBody, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, 0.25f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, -0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.5f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, -0.4f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, -0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.3f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, -2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -2.0f, 0.0f, -0.75f);
        this.animator.rotate(this.RightCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.5f, 0.0f, 0.5f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.TopBody, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, -0.25f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, -0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, 0.4f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, -0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.3f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateDownwardSlash() {
        this.animator.setAnim(7);
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, -0.2f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.1f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.1f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.0f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.move(this.Torso, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, -1.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Torso, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -1.5f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.55f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateStun() {
        this.animator.setAnim(8);
        this.animator.startPhase(0);
        this.animator.move(this.Torso, 0.0f, 1.0f, -3.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -2.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -3.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, -0.5f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 1.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 4.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 4.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Torso, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem, 3.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 1.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 4.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 4.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.75f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 3.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 0.0f, 0.0f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.25f, 0.25f);
        this.animator.rotate(this.LeftThigh, -0.25f, -0.25f, -0.25f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.25f, 1.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.25f, -1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(60);
        this.animator.resetPhase(20);
    }

    private void animateSidewaySlash() {
        this.animator.setAnim(9);
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.1f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.1f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.0f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.25f, 0.5f, -0.5f);
        this.animator.rotate(this.MiddleBody, -0.25f, 0.5f, -0.5f);
        this.animator.rotate(this.Torso, -0.25f, 0.5f, -0.5f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, -1.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -1.5f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, -0.25f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, -0.25f);
        this.animator.rotate(this.Torso, 1.0f, -0.25f, -0.5f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.0f, -1.0f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, 0.5f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 2.0f, 0.0f, -0.5f);
        this.animator.endPhase();
        this.animator.resetPhase(40);
    }

    private void animateDeath() {
        this.animator.setAnim(10);
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -0.5f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 2.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -0.5f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 2.0f, 9.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 9.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 9.0f);
        this.animator.rotate(this.RightThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.35f, 0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.35f, -0.4f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 2.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(80);
        this.animator.move(this.Torso, 0.0f, 10.0f, 1.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 1.75f, -0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, 1.75f, 0.5f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.9f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 1.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftShoulder, -1.5f, 0.0f, 0.5f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.25f, 0.0f, 0.0f);
        this.animator.move(this.HeldItem, 0.0f, 0.0f, 30.0f);
        this.animator.endPhase();
        this.animator.startPhase(100);
        this.animator.move(this.Torso, 0.0f, 10.0f, 1.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 1.6f, -0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, 1.6f, 0.5f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.9f, 0.0f);
        this.animator.rotate(this.TopBody, -0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 1.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.3f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftShoulder, -1.3f, 0.0f, 0.5f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.HeldItem, 0.0f, 0.0f, 30.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(1700);
        this.animator.resetPhase(0);
    }

    private void animateRoar() {
        this.animator.setAnim(11);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem, 0.0f, 0.0f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.25f, 0.25f);
        this.animator.rotate(this.LeftThigh, -0.25f, -0.25f, -0.25f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.25f, 1.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.25f, -1.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.25f, 0.25f);
        this.animator.rotate(this.LeftThigh, -0.25f, -0.25f, -0.25f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.25f, 1.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.25f, -1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(140);
        this.animator.resetPhase(40);
    }

    private void animateRangedAttackThrow() {
        this.animator.setAnim(12);
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, -1.5f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.75f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.75f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.0f, 0.8f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, -0.8f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, -0.8f);
        this.animator.rotate(this.LeftForearm, -0.25f, 0.0f, 0.8f);
        this.animator.rotate(this.HeldItem, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateBirth() {
        this.animator.setAnim(13);
        this.animator.startPhase(0);
        this.animator.move(this.Torso, 0.0f, 42.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 42.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 42.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.8f, -0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -0.8f, 0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(15);
        this.animator.move(this.Torso, 0.0f, 32.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 32.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 32.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.8f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -0.8f, -0.5f, 0.0f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(30);
        this.animator.move(this.Torso, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 20.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.5f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -3.0f, 0.5f, -0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.75f, 0.5f);
        this.animator.rotate(this.RightForearm, -0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 20.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.5f, -0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, 0.5f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(30);
        this.animator.move(this.Torso, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 20.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.25f, -0.5f);
        this.animator.rotate(this.LeftShoulder, -3.0f, -0.5f, 0.5f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 20.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.5f, -0.5f);
        this.animator.rotate(this.LeftShoulder, -1.0f, -0.5f, 0.5f);
        this.animator.rotate(this.RightForearm, -0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 20.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.5f, -0.5f);
        this.animator.rotate(this.LeftShoulder, -1.0f, -0.5f, 0.5f);
        this.animator.rotate(this.RightForearm, -0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(40);
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 20.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.5f, -0.5f);
        this.animator.rotate(this.LeftShoulder, -1.0f, -0.5f, 0.5f);
        this.animator.rotate(this.RightForearm, -0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 20.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, -1.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.5f, -0.5f);
        this.animator.rotate(this.LeftShoulder, -1.0f, -0.5f, 0.5f);
        this.animator.rotate(this.RightForearm, -0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 20.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.5f, -0.5f);
        this.animator.rotate(this.LeftShoulder, -1.0f, -0.5f, 0.5f);
        this.animator.rotate(this.RightForearm, -0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 20.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.5f, -0.5f);
        this.animator.rotate(this.LeftShoulder, -0.2f, -0.5f, 0.5f);
        this.animator.rotate(this.RightForearm, -0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 20.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 20.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.5f, -0.5f);
        this.animator.rotate(this.LeftShoulder, -0.5f, -0.5f, 0.5f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.8f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 12.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 12.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 12.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.8f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 8.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 8.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 8.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 4.0f, -4.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, -4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, -4.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, 0.5f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 0.0f, -2.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, -2.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, -2.0f);
        this.animator.rotate(this.RightThigh, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(40);
    }
}
