package net.minecraft.theTitans.models;


import com.mojang.blaze3d.matrix.MatrixStack;
import com.mojang.blaze3d.vertex.IVertexBuilder;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.entity.titan.EntitySkeletonTitan;
import net.minecraft.entity.titan.EntityZombieTitan;
import net.minecraft.util.math.MathHelper;
import thehippomaster.AnimationAPI.IAnimatedEntity;
import thehippomaster.AnimationAPI.client.Animator;

public class ModelSkeletonTitan extends EntityModel<EntitySkeletonTitan> {
    private final Animator animator;
    public ModelRenderer Hips;
    public ModelRenderer LeftThigh;
    public ModelRenderer RightThigh;
    public ModelRenderer Spine1;
    public ModelRenderer Spine2;
    public ModelRenderer Spine3;
    public ModelRenderer Spine4;
    public ModelRenderer Spine5;
    public ModelRenderer Spine6;
    public ModelRenderer Ribs;
    public ModelRenderer Head;
    public ModelRenderer LeftShoulder;
    public ModelRenderer RightShoulder;
    public ModelRenderer LeftForearm;
    public ModelRenderer RightForearm;
    public ModelRenderer HeldItem;
    public ModelRenderer HeldItem2;
    public ModelRenderer LeftFemur;
    public ModelRenderer RightFemur;
    public boolean isWither;
    private float partialTick;

    public ModelSkeletonTitan() {
        this(0.0f);
    }

    public ModelSkeletonTitan(final float p_i1147_1_) {
        this.texWidth = 64;
        this.texHeight = 64;
        (this.RightShoulder = new ModelRenderer(this, 40, 16)).setPos(-5.0f, -0.5f, 0.0f);
        this.RightShoulder.addBox(-1.0f, -2.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        (this.RightThigh = new ModelRenderer(this, 0, 16)).setPos(-2.0f, 12.0f, 0.0f);
        this.RightThigh.addBox(-1.0f, 0.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        (this.Spine3 = new ModelRenderer(this, 10, 26)).setPos(0.0f, -2.0f, 0.0f);
        this.Spine3.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 1, p_i1147_1_);
        this.LeftFemur = new ModelRenderer(this, 0, 24);
        this.LeftFemur.mirror = true;
        this.LeftFemur.setPos(0.0f, 6.0f, 0.0f);
        this.LeftFemur.addBox(-1.0f, 0.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        (this.RightForearm = new ModelRenderer(this, 40, 24)).setPos(0.0f, 4.0f, 0.0f);
        this.RightForearm.addBox(-1.0f, 0.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        (this.Spine4 = new ModelRenderer(this, 10, 24)).setPos(0.0f, -2.0f, 0.0f);
        this.Spine4.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 1, p_i1147_1_);
        (this.Spine1 = new ModelRenderer(this, 10, 30)).setPos(0.0f, 0.0f, 1.5f);
        this.Spine1.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 1, p_i1147_1_);
        (this.Hips = new ModelRenderer(this, 16, 27)).setPos(0.0f, 12.0f, 0.0f);
        this.Hips.addBox(-4.0f, -2.0f, -2.0f, 8, 2, 4, p_i1147_1_);
        (this.RightFemur = new ModelRenderer(this, 0, 16)).setPos(0.0f, 6.0f, 0.0f);
        this.RightFemur.addBox(-1.0f, 0.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        this.LeftShoulder = new ModelRenderer(this, 40, 16);
        this.LeftShoulder.mirror = true;
        this.LeftShoulder.setPos(5.0f, -0.5f, 0.0f);
        this.LeftShoulder.addBox(-1.0f, -2.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        this.LeftThigh = new ModelRenderer(this, 0, 16);
        this.LeftThigh.mirror = true;
        this.LeftThigh.setPos(1.9f, 12.0f, 0.1f);
        this.LeftThigh.addBox(-1.0f, 0.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        (this.Spine5 = new ModelRenderer(this, 10, 23)).setPos(0.0f, -2.0f, 0.0f);
        this.Spine5.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 1, p_i1147_1_);
        (this.Spine6 = new ModelRenderer(this, 10, 22)).setPos(0.0f, -2.0f, 0.0f);
        this.Spine6.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 1, p_i1147_1_);
        this.LeftForearm = new ModelRenderer(this, 40, 24);
        this.LeftForearm.mirror = true;
        this.LeftForearm.setPos(0.0f, 4.0f, 0.0f);
        this.LeftForearm.addBox(-1.0f, 0.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        (this.Spine2 = new ModelRenderer(this, 10, 28)).setPos(0.0f, -2.0f, 0.0f);
        this.Spine2.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 1, p_i1147_1_);
        (this.Ribs = new ModelRenderer(this, 16, 16)).setPos(0.0f, 1.0f, -1.5f);
        this.Ribs.addBox(-4.0f, -3.0f, -2.0f, 8, 7, 4, p_i1147_1_);
        (this.Head = new ModelRenderer(this, 0, 0)).setPos(0.0f, -3.0f, 0.0f);
        this.Head.addBox(-4.0f, -8.0f, -4.0f, 8, 8, 8, p_i1147_1_);
        (this.HeldItem = new ModelRenderer(this, 32, -16)).setPos(0.0f, 4.0f, 0.0f);
        this.HeldItem.addBox(0.0f, -6.0f, -10.0f, 0, 16, 16, 0.0f);
        (this.HeldItem2 = new ModelRenderer(this, 32, 17)).setPos(0.0f, 4.0f, 0.0f);
        this.HeldItem2.addBox(0.0f, -12.5f, -12.5f, 0, 16, 16, 0.0f);
        this.Ribs.addChild(this.RightShoulder);
        this.Spine2.addChild(this.Spine3);
        this.LeftThigh.addChild(this.LeftFemur);
        this.RightShoulder.addChild(this.RightForearm);
        this.Spine3.addChild(this.Spine4);
        this.Hips.addChild(this.Spine1);
        this.RightThigh.addChild(this.RightFemur);
        this.RightForearm.addChild(this.HeldItem);
        this.RightForearm.addChild(this.HeldItem2);
        this.Ribs.addChild(this.LeftShoulder);
        this.Spine4.addChild(this.Spine5);
        this.Spine5.addChild(this.Spine6);
        this.LeftShoulder.addChild(this.LeftForearm);
        this.Spine1.addChild(this.Spine2);
        this.Spine6.addChild(this.Ribs);
        this.Ribs.addChild(this.Head);
        this.animator = new Animator(this);
    }

    @Override
    public void prepareMobModel(EntitySkeletonTitan p_212843_1_, float p_212843_2_, float p_212843_3_, float p_212843_4_) {
        this.partialTick = p_212843_4_;
        super.prepareMobModel(p_212843_1_, p_212843_2_, p_212843_3_, p_212843_4_);
    }

    public void setupAnim(final EntitySkeletonTitan entity, final float f, final float f1, final float f2, final float f3, final float f4) {
        final EntitySkeletonTitan entitytitan = (EntitySkeletonTitan) entity;
        this.resetAngles();
        this.animate((IAnimatedEntity) entity, f, f1, f2, f3, f4);
        if (entitytitan.getSkeletonType() == 1) {
            this.isWither = true;
            this.HeldItem.visible = false;
            this.HeldItem2.visible = true;
        } else {
            this.isWither = false;
            this.HeldItem.visible = true;
            this.HeldItem2.visible = false;
        }
    }

    private void resetAngles() {
        Animator.resetAngles(this.Head);
        Animator.resetAngles(this.LeftShoulder, this.LeftForearm);
        Animator.resetAngles(this.RightShoulder, this.RightForearm, this.HeldItem);
        Animator.resetAngles(this.Hips, this.Spine1, this.Spine2, this.Spine3, this.Spine4, this.Spine5, this.Spine6, this.Ribs);
        Animator.resetAngles(this.LeftThigh, this.LeftFemur);
        Animator.resetAngles(this.RightThigh, this.RightFemur);
    }

    @Override
    public void renderToBuffer(MatrixStack p_225598_1_, IVertexBuilder p_225598_2_, int p_225598_3_, int p_225598_4_, float p_225598_5_, float p_225598_6_, float p_225598_7_, float p_225598_8_) {
        this.Hips.render(p_225598_1_, p_225598_2_, p_225598_3_, p_225598_4_, p_225598_5_, p_225598_6_, p_225598_7_, p_225598_8_);
        this.LeftThigh.render(p_225598_1_, p_225598_2_, p_225598_3_, p_225598_4_, p_225598_5_, p_225598_6_, p_225598_7_, p_225598_8_);
        this.RightThigh.render(p_225598_1_, p_225598_2_, p_225598_3_, p_225598_4_, p_225598_5_, p_225598_6_, p_225598_7_, p_225598_8_);
    }

    public void setAngles() {
        this.Head.x = 0.0f;
        this.Head.y = -3.0f;
        this.Head.z = 0.0f;
        this.HeldItem.x = 0.0f;
        this.HeldItem.y = 4.0f;
        this.HeldItem.z = 0.0f;
        this.HeldItem2.z = 0.0f;
        this.HeldItem2.x = 0.0f;
        this.HeldItem2.y = 4.0f;
        this.Hips.x = 0.0f;
        this.RightThigh.x = -2.0f;
        this.LeftThigh.x = 2.0f;
        this.Hips.z = 0.0f;
        this.RightThigh.z = 0.0f;
        this.LeftThigh.z = 0.0f;
        this.Hips.y = 12.0f;
        this.RightThigh.y = 12.0f;
        this.LeftThigh.y = 12.0f;
        this.setRotateAngle(this.LeftForearm, -0.17453292f, 0.0f, 0.0f);
        this.setRotateAngle(this.LeftShoulder, 0.08726646f, -0.08726646f, -0.08726646f);
        this.setRotateAngle(this.RightFemur, 0.13962634f, 0.0f, 0.0f);
        this.setRotateAngle(this.RightForearm, -0.17453292f, 0.0f, 0.0f);
        this.setRotateAngle(this.LeftFemur, 0.13962634f, 0.0f, 0.0f);
        this.setRotateAngle(this.LeftThigh, -0.06981317f, -0.06981317f, 0.0f);
        this.setRotateAngle(this.RightThigh, -0.08726646f, 0.06981317f, 0.0f);
        this.setRotateAngle(this.RightShoulder, 0.08726646f, 0.08726646f, 0.08726646f);
        this.setRotateAngle(this.HeldItem, -2.3561945f, 0.0f, 0.0f);
        this.setRotateAngle(this.HeldItem2, 0.7853982f, 0.0f, 0.0f);
    }

    public void setRotateAngle(final ModelRenderer modelRenderer, final float x, final float y, final float z) {
        modelRenderer.xRot = x;
        modelRenderer.yRot = y;
        modelRenderer.zRot = z;
    }

    public void animate(final IAnimatedEntity entity, final float f, float f1, final float f2, final float f3, final float f4) {
        this.animator.update(entity, this.partialTick);
        this.setAngles();
        final EntitySkeletonTitan entitytitan = (EntitySkeletonTitan) entity;
        final float fo = 0.6662f / ((entitytitan.getSkeletonType() == 1) ? 2.5f : 4.0f);
        if (entitytitan.deathTicks <= 0) {
            final float f6 = MathHelper.cos(f2 * 0.1f);
            if (entitytitan.animID == 0) {
                this.Spine3.xRot = (0.001f + 0.0025f * f6) * 3.1415927f;
                this.Spine4.xRot = (0.001f + 0.0025f * f6) * 3.1415927f;
                this.Spine5.xRot = (0.001f + 0.0025f * f6) * 3.1415927f;
                this.Spine6.xRot = (0.001f + 0.0025f * f6) * 3.1415927f;
                this.Head.xRot = (0.001f + 0.005f * f6) * 3.1415927f;
                this.RightShoulder.zRot = (0.025f + 0.025f * f6) * 3.1415927f;
                this.LeftShoulder.zRot = (-0.025f + -0.025f * f6) * 3.1415927f;
            }
            if (this.riding) {
                this.RightThigh.xRot = -1.5707964f;
                this.LeftThigh.xRot = -1.5707964f;
                this.RightThigh.yRot = 0.31415927f;
                this.LeftThigh.yRot = -0.31415927f;
                this.RightFemur.xRot = 1.0471976f;
                this.LeftFemur.xRot = 1.0471976f;
            } else if (entitytitan.getAnimID() == 0) {
                this.Hips.y = 12.0f - MathHelper.cos(f * (fo * 2.0f) + 1.0f) * 2.0f * f1;
                this.RightThigh.y = 12.0f - MathHelper.cos(f * (fo * 2.0f) + 1.0f) * 2.0f * f1;
                this.LeftThigh.y = 12.0f - MathHelper.cos(f * (fo * 2.0f) + 1.0f) * 2.0f * f1;
                this.Head.zRot = MathHelper.cos(f * fo + 3.25f) * 0.3f * f1;
                this.Spine6.zRot = MathHelper.cos(f * fo - 3.0f) * 0.1f * f1;
                this.Spine5.zRot = MathHelper.cos(f * fo - 2.5f) * 0.1f * f1;
                this.Spine4.zRot = MathHelper.cos(f * fo - 2.0f) * 0.1f * f1;
                this.Spine3.zRot = MathHelper.cos(f * fo - 1.5f) * 0.1f * f1;
                this.Spine2.zRot = MathHelper.cos(f * fo - 1.0f) * 0.1f * f1;
                this.Spine1.zRot = MathHelper.cos(f * fo - 0.5f) * 0.1f * f1;
                this.Hips.zRot = MathHelper.cos(f * fo) * 0.2f * f1;
                this.RightThigh.xRot = -0.08726646f + MathHelper.cos(f * fo - 0.5f) * 0.75f * f1;
                this.LeftThigh.xRot = -0.08726646f + MathHelper.cos(f * fo + 2.6415927f) * 0.75f * f1;
                this.RightFemur.xRot = 0.13962634f + MathHelper.cos(f * fo + 3.1415927f) * 0.75f * f1;
                this.LeftFemur.xRot = 0.13962634f + MathHelper.cos(f * fo) * 0.75f * f1;
                if (this.RightFemur.xRot < 0.13962634f) {
                    this.RightFemur.xRot = 0.13962634f;
                }
                if (this.LeftFemur.xRot < 0.13962634f) {
                    this.LeftFemur.xRot = 0.13962634f;
                }
                if (!this.riding) {
                    this.RightShoulder.xRot = 0.08726646f + MathHelper.cos(f * fo + 3.1415927f) * 1.0f * f1;
                    this.LeftShoulder.xRot = 0.08726646f + MathHelper.cos(f * fo) * 1.0f * f1;
                    this.RightForearm.xRot = -0.17453292f + MathHelper.cos(f * fo + 2.1415927f) * 1.0f * f1;
                    this.LeftForearm.xRot = -0.17453292f + MathHelper.cos(f * fo - 1.0f) * 1.0f * f1;
                    if (this.RightForearm.xRot > -0.17453292f) {
                        this.RightForearm.xRot = -0.17453292f;
                    }
                    if (this.LeftForearm.xRot > -0.17453292f) {
                        this.LeftForearm.xRot = -0.17453292f;
                    }
                }
            }
            final float faceYaw = f3 * 3.1415927f / 180.0f;
            final float facePitch = f4 * 3.1415927f / 180.0f;
            if (entitytitan.animID == 0) {
                final ModelRenderer head = this.Head;
                head.xRot += facePitch * 0.5f;
                final ModelRenderer head2 = this.Head;
                head2.yRot += faceYaw * 0.5f;
                final ModelRenderer spine6 = this.Spine6;
                spine6.xRot += facePitch * 0.1f;
                final ModelRenderer spine7 = this.Spine6;
                spine7.yRot += faceYaw * 0.1f;
                final ModelRenderer spine8 = this.Spine5;
                spine8.xRot += facePitch * 0.1f;
                final ModelRenderer spine9 = this.Spine5;
                spine9.yRot += faceYaw * 0.1f;
                final ModelRenderer spine10 = this.Spine4;
                spine10.xRot += facePitch * 0.1f;
                final ModelRenderer spine11 = this.Spine4;
                spine11.yRot += faceYaw * 0.1f;
                final ModelRenderer spine12 = this.Spine3;
                spine12.xRot += facePitch * 0.1f;
                final ModelRenderer spine13 = this.Spine3;
                spine13.yRot += faceYaw * 0.1f;
                final ModelRenderer rightShoulder = this.RightShoulder;
                rightShoulder.xRot -= facePitch * 0.4f;
                final ModelRenderer leftShoulder = this.LeftShoulder;
                leftShoulder.xRot -= facePitch * 0.4f;
            } else {
                final ModelRenderer head3 = this.Head;
                head3.xRot += facePitch * 0.9f;
                final ModelRenderer head4 = this.Head;
                head4.yRot += faceYaw * 0.9f;
            }
            if (!entitytitan.isOnGround() && !this.riding) {
                this.Spine6.zRot = 0.0f;
                this.Spine5.zRot = 0.0f;
                this.Spine4.zRot = 0.0f;
                this.Spine3.zRot = 0.0f;
                this.Spine2.zRot = 0.0f;
                this.Spine1.zRot = 0.0f;
                this.Hips.zRot = 0.0f;
                this.Head.zRot = 0.0f;
                this.RightShoulder.xRot = -entitytitan.animationSpeed;
                this.LeftShoulder.xRot = -entitytitan.animationSpeed;
                this.RightForearm.xRot = -(entitytitan.animationSpeed / 2.0f);
                this.LeftForearm.xRot = -(entitytitan.animationSpeed / 2.0f);
                final ModelRenderer head5 = this.Head;
                head5.xRot -= entitytitan.animationSpeed;
                final ModelRenderer hips = this.Hips;
                hips.xRot += entitytitan.animationSpeed;
                this.RightThigh.zRot = 0.25f;
                this.LeftThigh.zRot = -0.25f;
                this.RightThigh.yRot = -0.25f;
                this.LeftThigh.yRot = 0.25f;
                this.RightThigh.xRot = MathHelper.cos(f2 * 0.2f) * 0.25f - (float) (entitytitan.getDeltaMovement().y / 5.0) + entitytitan.animationSpeed;
                this.LeftThigh.xRot = MathHelper.cos(f2 * 0.2f - 3.1415927f) * 0.25f - (float) (entitytitan.getDeltaMovement().y / 5.0) + entitytitan.animationSpeed;
                this.RightFemur.xRot = 0.5f - MathHelper.cos(f2 * 0.2f + 0.5f) * 0.5f;
                this.LeftFemur.xRot = 0.5f - MathHelper.cos(f2 * 0.2f - 2.6415927f) * 0.5f;
            }
            if (entitytitan.getAnimID() == 5 && entitytitan.getAnimTick() > 100 && entitytitan.getAnimTick() < 300) {
                this.LeftForearm.xRot = -MathHelper.cos(f2 * 4.0f) * 0.5f;
            }
            if (entitytitan.getAnimID() == 1) {
                switch (entitytitan.antiTitanAttackAnimeID) {
                    case 0: {
                        this.animateAntiTitanAttack1();
                        break;
                    }
                    case 1: {
                        this.animateAntiTitanAttack2();
                        break;
                    }
                    case 2: {
                        this.animateAntiTitanAttack3();
                        break;
                    }
                    case 3: {
                        this.animateAntiTitanAttack4();
                        break;
                    }
                }
            }
            this.animatePunch();
            this.animateBackhand();
            this.animateSwat();
            this.animateShot();
            this.animateStomp();
            this.animateDownwardSlash();
            this.animateStun();
            this.animateLightning();
            this.animateGiantShot();
            this.animateLightningHand();
            this.animateBirth();
        } else {
            this.animateDeath();
        }
    }

    private void animateStun() {
        this.animator.setAnim(8);
        this.animator.startPhase(0);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -3.0f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.5f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Hips, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, -1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -2.6f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 9.8f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.6f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.6f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.3f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.3f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 1.6f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(200);
        this.animator.startPhase(70);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 9.8f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.6f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.6f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.3f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.3f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 1.6f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 9.8f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -4.0f, -0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -4.0f, 0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.2f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -0.2f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 1.6f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, -20.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -20.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, -20.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, -0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.3f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 4.0f, 2.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 2.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 2.0f);
        this.animator.rotate(this.RightThigh, -0.9f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.9f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.8f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 4.0f, 2.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 2.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 2.0f);
        this.animator.rotate(this.RightThigh, -0.9f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.9f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.8f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(30);
    }

    private void animateSwat() {
        this.animator.setAnim(2);
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.0f, 0.75f, 1.5f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, -1.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 6.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -1.0f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.0f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.0f, -1.25f, -1.5f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.375f, 1.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateBackhand() {
        this.animator.setAnim(4);
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -2.5f, -0.75f, -1.5f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, 1.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 6.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -1.0f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.0f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.5f, 0.75f, 1.5f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.375f, -1.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animatePunch() {
        this.animator.setAnim(3);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.1f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Ribs, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.6f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.6f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.2f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateLightning() {
        this.animator.setAnim(9);
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.25f, -0.6f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.35f, -0.25f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.25f, 0.6f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.35f, 0.25f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 0.0f, 0.5f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(5);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, -0.6f, 0.0f);
        this.animator.rotate(this.RightForearm, -1.0f, -0.25f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.0f, 0.6f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.25f, 0.0f);
        this.animator.rotate(this.HeldItem2, -1.0f, 0.0f, 0.5f);
        this.animator.rotate(this.Spine6, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.6f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.25f, -0.6f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.35f, -0.25f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.25f, 0.6f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.35f, 0.25f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 0.0f, 0.5f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack1() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.9f, 0.0f, 1.0f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 1.0f);
        this.animator.rotate(this.HeldItem2, 1.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.HeldItem, 0.0f, 100.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -8.0f);
        this.animator.rotate(this.RightThigh, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -2.0f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 2.0f, 10.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 100.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.HeldItem, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(0);
    }

    private void animateAntiTitanAttack2() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.25f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.25f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 2.0f, -8.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, -8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, -8.0f);
        this.animator.rotate(this.RightThigh, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.6f, -0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.4f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(0);
    }

    private void animateAntiTitanAttack3() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.5f, -1.5f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine2, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine1, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.0f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.5f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 2.0f, -8.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, -8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, -8.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 1.5f, 0.0f);
        this.animator.rotate(this.Spine6, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine5, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine4, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine3, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine2, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine1, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.5f, -0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(0);
    }

    private void animateAntiTitanAttack4() {
        this.animator.setAnim(1);
        this.animator.startPhase(8);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.25f, -0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.25f, 0.4f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(12);
        this.animator.move(this.Hips, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.0f);
        this.animator.rotate(this.RightThigh, 1.8f, -10.0f, 0.5f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftThigh, -0.5f, -10.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.25f, -0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.25f, 0.4f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 1.75f, -10.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, 0.0f, -12.6f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, -12.6f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, -12.6f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(0);
    }

    private void animateShot() {
        this.animator.setAnim(5);
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.35f, 0.5f, -1.5f);
        this.animator.rotate(this.LeftShoulder, -1.2f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, -0.3f);
        this.animator.rotate(this.LeftForearm, -0.4f, 0.0f, 1.5f);
        this.animator.rotate(this.HeldItem, 1.0f, 2.5f, 1.0f);
        this.animator.rotate(this.Spine1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(300);
        this.animator.resetPhase(30);
    }

    private void animateStomp() {
        this.animator.setAnim(6);
        this.animator.startPhase(25);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.6f, 0.2f, 0.75f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.2f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.5f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.5f);
        this.animator.rotate(this.Spine6, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, 0.8f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.5f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, -0.8f);
        this.animator.rotate(this.RightShoulder, 0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, -2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -2.6f, 0.0f, -0.75f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.5f, 0.0f, 0.5f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Spine6, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, -0.8f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.5f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, 0.8f);
        this.animator.rotate(this.RightShoulder, 0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateDownwardSlash() {
        this.animator.setAnim(7);
        this.animator.startPhase(60);
        this.animator.move(this.HeldItem, 0.0f, 2.0f, -6.0f);
        this.animator.move(this.Hips, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Hips, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem2, 0.5f, 0.5f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.startPhase(30);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -3.0f, 0.0f, -0.875f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(50);
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -3.0f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 50.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 3.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Spine6, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(40);
    }

    private void animateDeath() {
        this.animator.setAnim(10);
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, 2.0f, 6.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 6.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 6.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0707964f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -1.0707964f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, 2.0f, 12.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 12.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 12.0f);
        this.animator.rotate(this.RightThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0707964f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -1.0707964f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, 2.0f, 12.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 12.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 12.0f);
        this.animator.rotate(this.RightThigh, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.5f, 0.5f);
        this.animator.rotate(this.Spine6, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.25f, -0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.25f, 0.4f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 2.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(80);
        this.animator.move(this.Hips, 0.0f, 10.0f, -3.0f);
        this.animator.move(this.Head, 0.0f, -12.0f, 2.5f);
        this.animator.move(this.RightThigh, 0.0f, 11.0f, 0.0f);
        this.animator.move(this.LeftThigh, 10.0f, 11.0f, 12.0f);
        this.animator.rotate(this.RightThigh, 1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.0f, 1.5f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 14.4f, 14.4f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 1.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.5f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -3.0f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 2.0f, 1.0f, 10.0f);
        this.animator.move(this.HeldItem, 0.0f, 0.0f, -10.0f);
        this.animator.move(this.HeldItem2, 0.0f, 0.0f, -10.0f);
        this.animator.endPhase();
        this.animator.startPhase(100);
        this.animator.move(this.Hips, 0.0f, 10.0f, -3.0f);
        this.animator.move(this.Head, 0.0f, -12.0f, -1.0f);
        this.animator.move(this.RightThigh, 0.0f, 11.0f, 0.0f);
        this.animator.move(this.LeftThigh, 10.0f, 11.0f, 12.0f);
        this.animator.rotate(this.RightThigh, 1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.0f, 1.5f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 14.4f, 14.4f, 0.0f);
        this.animator.rotate(this.Spine6, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 1.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -3.0f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, 0.15f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.15f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 2.0f, 1.0f, 10.0f);
        this.animator.move(this.HeldItem, 0.0f, 0.0f, -10.0f);
        this.animator.move(this.HeldItem2, 0.0f, 0.0f, -10.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(1700);
        this.animator.resetPhase(0);
    }

    private void animateGiantShot() {
        this.animator.setAnim(11);
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.35f, 0.5f, -1.5f);
        this.animator.rotate(this.LeftShoulder, -1.2f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, -0.3f);
        this.animator.rotate(this.LeftForearm, -0.4f, 0.0f, 1.5f);
        this.animator.rotate(this.HeldItem, 1.0f, 2.5f, 1.0f);
        this.animator.rotate(this.Spine1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(50);
        this.animator.startPhase(5);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.35f, 0.5f, -1.5f);
        this.animator.rotate(this.LeftShoulder, -1.6f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, -0.3f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 1.5f);
        this.animator.rotate(this.HeldItem, 1.0f, 2.5f, 1.0f);
        this.animator.rotate(this.Spine1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.35f, 0.5f, -1.5f);
        this.animator.rotate(this.LeftShoulder, -1.2f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, -0.3f);
        this.animator.rotate(this.LeftForearm, -0.4f, 0.0f, 1.5f);
        this.animator.rotate(this.HeldItem, 1.0f, 2.5f, 1.0f);
        this.animator.rotate(this.Spine1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.resetPhase(20);
    }

    private void animateLightningHand() {
        this.animator.setAnim(12);
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.RightThigh, 2.0f, 0.0f, 2.0f);
        this.animator.move(this.LeftThigh, -2.0f, 0.0f, -2.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 1.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.0f, -1.8f, 0.0f);
        this.animator.rotate(this.RightForearm, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 1.8f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, -1.8f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.startPhase(2);
        this.animator.move(this.RightThigh, 2.0f, 0.0f, 2.0f);
        this.animator.move(this.LeftThigh, -2.0f, 0.0f, -2.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 1.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.0f, -1.8f, 0.0f);
        this.animator.rotate(this.RightForearm, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 1.8f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, -1.8f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(8);
        this.animator.move(this.RightThigh, 2.0f, 0.0f, 2.0f);
        this.animator.move(this.LeftThigh, -2.0f, 0.0f, -2.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 1.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.0f, -1.8f, 0.0f);
        this.animator.rotate(this.RightForearm, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 1.8f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, -1.8f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.resetPhase(10);
    }

    private void animateBirth() {
        this.animator.setAnim(13);
        this.animator.startPhase(0);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.4f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.9f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -1.55f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.1f, 0.0f, 0.25f);
        this.animator.rotate(this.LeftShoulder, 0.1f, 0.0f, -0.25f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 1.6f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(160);
        this.animator.startPhase(60);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 9.5f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.5f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.9f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -1.55f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.1f, 0.0f, 0.25f);
        this.animator.rotate(this.LeftShoulder, 2.5f, 2.5f, 0.25f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 1.6f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.4f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.9f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -1.55f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.1f, 0.0f, 0.25f);
        this.animator.rotate(this.LeftShoulder, 2.5f, 1.5f, 0.2f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 1.6f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(40);
        this.animator.startPhase(60);
        this.animator.move(this.Hips, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.9f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.9f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 1.5f, 0.75f, 0.25f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.move(this.Hips, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.9f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.9f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(120);
        this.animator.move(this.Hips, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -2.0f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.125f, 0.125f, 0.0f);
        this.animator.rotate(this.Spine5, -0.125f, 0.125f, 0.0f);
        this.animator.rotate(this.Spine4, -0.125f, 0.125f, 0.0f);
        this.animator.rotate(this.Spine3, -0.125f, 0.125f, 0.0f);
        this.animator.rotate(this.Spine2, -0.125f, 0.125f, 0.0f);
        this.animator.rotate(this.Spine1, -0.125f, 0.125f, 0.0f);
        this.animator.rotate(this.Hips, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, 4.0f, 3.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 3.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 3.0f);
        this.animator.rotate(this.RightThigh, -1.25f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, 1.0f, -2.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -2.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -2.0f);
        this.animator.rotate(this.RightThigh, 0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.RightThigh, -0.125f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.125f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.125f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.125f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.125f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Spine6, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.1f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.125f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.125f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.3f, -0.5f, 0.0f);
        this.animator.rotate(this.Spine6, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.05f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.resetPhase(40);
    }
}
